version: '2'

services:
  janus-gateway:
    image: linagora/janus-gateway
    ports:
      - "7088:7088"
      - "8088:8088"
      - "8188:8188"
      - "8089:8089"
      - "10000-10200:10000-10200/udp"
    environment:
      - DOCKER_IP=${DOCKER_IP}

  nginx:
    build: ./nginx
    volumes:
      - ./samplecode/:/samplecode/
    ports:
      - 81:81
    depends_on:
      - janus-gateway


